import { mkdir, cp, readFile, writeFile, rm, readdir } from 'node:fs/promises';
import { build } from 'esbuild';
import Papa from 'papaparse';

await rm('public', { recursive: true, force: true });
await mkdir('public/assets', { recursive: true });
for (const file of ['index.html', 'add-activity.html', 'app.js', 'style.css', 'style-additions.css', 'teaching.js', 'teaching-styles.css', '_headers', 'cv-studio.css', 'CHANGELOG.md', 'README.md', 'data']) {
  await cp(file, `public/${file}`, { recursive: true });
}
const csv = await readFile('data/faculty.csv', 'utf8');
const rows = Papa.parse(csv, { header: true, skipEmptyLines: true }).data;
const ids = [...new Set(rows.map(row => String(row.id || '').trim()).filter(id => /^\d{1,12}$/.test(id)))];
await writeFile('src/faculty-roster.json', JSON.stringify(ids));
// The PDF function carries its own fonts. Reading them from the deployed file
// system would depend on the bundler's layout; embedding the bytes does not.
const fontFiles = (await readdir('assets/fonts')).filter(name => /\.(ttf|otf)$/i.test(name)).sort();
const fontBlobs = await Promise.all(fontFiles.map(async name => (await readFile(`assets/fonts/${name}`)).toString('base64')));
await writeFile('src/cv-fonts.generated.mjs',
  `// Generated by scripts/build-site.mjs — do not edit.\nexport const FONT_BLOBS = ${JSON.stringify(fontBlobs)};\n`);

await build({ entryPoints: ['src/cv-studio.mjs'], outfile: 'public/assets/cv-studio.js', bundle: true, minify: true, target: 'es2020', format: 'iife', loader: { '.css': 'text' } });
await build({ entryPoints: ['src/cv-word.mjs'], outfile: 'public/assets/cv-word.js', bundle: true, minify: true, target: 'es2020', format: 'esm' });
console.log(`Built site and academic CV exports (${ids.length} faculty IDs, ${fontFiles.length} embedded fonts).`);
